services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile.backend
    depends_on:
      - database
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/root/backend
    working_dir: /root/backend
    # command: cargo run
    command: tail -f /dev/null
    restart: always
    networks:
      - uav

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    depends_on:
      - database
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/root/frontend
    working_dir: /root/frontend
    environment:
      - HOST=0.0.0.0
    restart: always
    networks:
      - uav

  database:
    container_name: database
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=moyanxinxu
      - MYSQL_DATABASE=uav
      - MYSQL_USER=moyanxinxu
      - MYSQL_PASSWORD=moyanxinxu
    ports:
      - "3306:3306"
    volumes:
      - ./save/mysql:/var/lib/mysql
      - ./backend/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - uav

networks:
  uav:
    driver: bridge

volumes:
  backend_target:
  node_modules: